apiVersion: apps/v1
kind: Deployment
metadata:
  name: myacr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myacr
  template:
    metadata:
      labels:
        app: myacr
    spec:
      containers:
        - name: myacr
          image: cont21.azurecr.io/docker-app:latest
          ports:
            - containerPort: 5000
