apiVersion: apps/v1
kind: Deployment
metadata:
  name: myacr
  namespace: kube21
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myacr
  template:
    metadata:
      labels:
        app: myacr
    spec:
      containers:
        - name: myacr
          image: container2218.azurecr.io/nag-image:prod
          ports:
            - containerPort: 5000
      imagePullsecrets:
      - name: nagacontainer
